### ISSUE TITLE
White Spaces in UI

### ISSUE THREAD

**Issue by Orrimp** [hiro-codes/bolt#74] opened 2023-04-13 06:24 UTC
Hi Hiro, 

I have insalled Bolt on my Mac and my UI looks a bit buggy :) 

<img width="1804" alt="image" src="https://user-images.githubusercontent.com/6703417/231671608-6e628013-184e-4db5-9fb9-60abe1dce337.png">

**Comment by 0xhiro** [comment] 2023-04-13 06:28
Hey! thanks for the report.
This is a known issue. It's quite difficult to fix because it is hard to reproduce. Sometimes the white bars show up and sometimes they don't, and the behavior seems random. Please let me know if you have any extra information about it. I'll keep this issue open to track this bug.

**Comment by 0xhiro** [comment] 2023-04-15 23:59
Hello there!
Can you try launching the app again?  Does the issue persist?

**Comment by Orrimp** [comment] 2023-04-16 17:30
@0xhiro  yes it does. How can I help you to debug it?

**Comment by 0xhiro** [comment] 2023-04-25 14:52
Hello there! This issue was fixed by @zemzale. Could you update to the latest version to verify that it is working?

**Comment by Orrimp** [comment] 2023-04-25 17:32
Works fine, its blue now :D 

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/6703417/234356589-c2ce2714-797a-4caf-90ca-5b701122ff13.png">

**Comment by 0xhiro** [comment] 2023-04-26 04:43
Yes!! the blue lines are the scrollbars :)

**Closed** 2023-04-29 19:00 UTC
Labels: bug, help wanted
